inherit_from:
  - https://raw.githubusercontent.com/standout/Coding/master/ruby/rubocop.yml

# Project specific settings
AllCops:
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - Gemfile
    - Guardfile
    - config/Guardfile
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - "spec/features/*"

Metrics/MethodLength:
  Exclude:
    - "spec/features/*"

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
