AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - Gemfile
    - Guardfile
    - Rakefile

Metrics/LineLength:
  Exclude:
    - "config/**/*"

Metrics/AbcSize:
  Exclude:
    - "spec/features/*"

Metrics/MethodLength:
  Exclude:
    - "spec/features/*"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
